version: '3.8'

services:
  python: 
    image: python:3.10
    tty: true
    volumes: 
      - ./src:/usr/src
      - ./requirements.txt:/usr/src/requirements.txt
    working_dir: /usr/src
    command: ["sh", "-c", "pip install -r requirements.txt && tail -f /dev/null"]